security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        App\Entity\Livreur:
            algorithm: bcrypt
        App\Entity\Fournisseur:
            algorithm: bcrypt
        App\Entity\Client:
            algorithm: bcrypt








    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Client
                property: email

        app_livreur_provider:
            entity:
                class: App\Entity\Livreur
                property: email

        app_admin_provider:
            entity:
              class: App\Entity\User
              property: username

        app_fournisseur_provider:
                    entity:
                        class: App\Entity\Fournisseur
                        property: email
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:

            anonymous: true
            provider: app_admin_provider


            logout:
                path: logout
                target: /


            guard:
                authenticators:
                    - App\Security\LoginFormAuthentificatorAuthenticator
                    - App\Security\LoginCliFormAuthenticator
                    - App\Security\FournisseurAuthAuthenticator
                entry_point: App\Security\LoginFormAuthentificatorAuthenticator

        cli:
            pattern: ^/client/
            security: false
        client:

            anonymous: true
            provider: app_user_provider


            logout:
                path: logoutcli
                target: /client
        four:
            pattern: ^/fournisseur/
            security: false
        fournisseur:

            anonymous: true
            provider: app_fournisseur_provider




            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/client/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/region, roles: ROLE_USER }
        - { path: ^/ville, roles: ROLE_USER }
        - { path: ^/condi, roles: ROLE_USER }
        - { path: ^/affcli, roles: ROLE_USER }
        - { path: ^/fournisseur, roles: ROLE_USER }
        - { path: ^/categorie, roles: ROLE_FOUR }
        - { path: ^/article, roles: ROLE_FOUR }
        - { path: ^/supplement, roles: ROLE_FOUR }
        # - { path: ^/profile, roles: ROLE_USER }
