vich_uploader:
    db_driver: orm

    mappings:
      article_image:
        uri_prefix: assets/images
        upload_destination: '%kernel.project_dir%/public/assets/images'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
